export const INPUT_KEY_UP = 'INPUT_KEY_UP'
export const INPUT_KEY_DOWN = 'INPUT_KEY_DOWN'

export const MIDI_NOTE_ON = 'MIDI_NOTE_ON'
export const MIDI_NOTE_OFF = 'MIDI_NOTE_OFF'
export const MIDI_CONTROL_CHANGE = 'MIDI_CONTROL_CHANGE'

export default {
  INPUT_KEY_UP,
  INPUT_KEY_DOWN,
  MIDI_NOTE_ON,
  MIDI_NOTE_OFF,
  MIDI_CONTROL_CHANGE,
}
